PUT http://localhost:8080/events/3
Content-Type: application/application/json

{
  "name": "Updated Event",
  "description": "Learn Go from scratch: structs, goroutines, and HTTP servers.(Updated)",
  "location": "DevSpace, 456 Coding Lane, Austin ",
  "dateTime": "2025-07-20T10:00:00.000Z"
}